# Generated by Django 5.1.6 on 2025-07-25 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_likepost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profileing',
            field=models.CharField(blank=True, default='blank-profile-picture.png', max_length=100),
        ),
    ]
