# Generated by Django 5.1.6 on 2025-07-25 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_alter_profile_profileing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='profileing',
        ),
        migrations.AddField(
            model_name='profile',
            name='profileimg',
            field=models.ImageField(default='profile_images/blank-profile-picture.png', upload_to='profile_images/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id_user',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
